name: Android CI

on:
  release:
    types: [published]
  push:
    branches:
      - master
    tags:
      - '1.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant rights
        run: chmod +x build.gradle

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Build Release APK
        id: buildRelease
        run: ./gradlew assembleRelease
